title: Mapping the Doctrine of Discovery Podcast
description: "The goal of this Podcast is to help identify these systems of domination that have been sustained by greed and power, through the subjugation of human beings and the natural world."
cover: /assets/images/mapping-doctrine-of-discovery-favicon.webp
logo: /assets/images/dod-podcast-logo.svg
url: https://podcast.doctrineofdiscovery.org

header:
  background: /assets/images/hero-background.webp
  cover: /assets/images/mapping-doctrine-of-discovery-favicon.webp
  title: Welcome to Mapping the Doctrine of Discovery Podcast
  description: Presented by the Indigenous Values Initiative.
  content: Helping listeners contextualize the Doctrine of Discovery.
  btn: Subscribe to Podcast
  btnurl: /subscribe/

subscribe:
  title: Subscribe
  btn: Subscribe →
  link: /subscribe/

podcast :
  title: Latest Episodes
  btn: Explore All
  url: /episodes/
  background: /assets/images/pattern.svg

patner:
  text: This project is supported by grants from the Hendricks Chapel Syracuse University and the Henry Luce Foundation.
  title: Partners
  
footer:
  logo: /assets/images/blue-olive.svg
  copyright1: This podcast is licensed under the <a href="https://creativecommons.org/licenses/by/4.0/deed.en">Creative Commons</a> by the <a href="https://indigenousvalues.org">Indigenous Values Initiative</a>.
  copyright2: This site was created with Stackbit and is maintained by <a href="https://adamdjbrett.com">Adam DJ Brett</a>.

social: 
  facebook: https://www.facebook.com/doctrineofdiscovery
  twitter: https://twitter.com/indigenousVI
  instagram: https://instagram.com/indigenousvalues
  youtube: https://youtube.com/c/IndigenousValuesInitiative
