title: Mapping the Doctrine of Discovery Podcast
description: "The goal of this Podcast is to help identify these systems of domination that have been sustained by greed and power, through the subjugation of human beings and the natural world."
cover: /assets/images/mapping-doctrine-of-discovery-favicon.webp
logo: /assets/images/dod-podcast-logo.svg
url: https://podcast.doctrineofdiscovery.org

header:
  background: /assets/images/hero-background.webp
  cover: /assets/images/mapping-doctrine-of-discovery-favicon.webp
  title: Welcome to Mapping the Doctrine of Discovery Podcast
  description: Presented by the Indigenous Values Initiative.
  content: Helping listeners contextualize the Doctrine of Discovery.
  btn: Subscribe to Podcast
  btnurl: /subscribe/

#notes:
# text: Notes by Adam DJ Brett
# url: "/authors/adamdjbrett/"

collections:
  authors:
    output: true

subscribe:
  title: Subscribe
  btn: Subscribe →
  link: /subscribe/

podcast :
  title: Latest Episodes
  btn: Explore All
  url: /episodes/
  background: /assets/images/pattern.svg

patner:
  text: This project is supported by grants from the Hendricks Chapel Syracuse University and the Henry Luce Foundation.
  title: Partners
  
footer:
  logo: /assets/images/blue-olive.svg
  copyright1: This podcast is licensed under the Creative Commons by the Indigenous Values Initiative.
  copyright2: This site was created with Stackbit and is maintained by Adam DJ Brett.

social: 
  facebook: https://www.facebook.com/doctrineofdiscovery
  twitter: https://twitter.com/indigenousVI
  instagram: https://instagram.com/indigenousvalues
  youtube: https://youtube.com/c/IndigenousValuesInitiative



defaults:
  # Tidak perlu set permalink di pages secara global!
  - scope:
      path: "pages"
    values:
      sitemap: false

  # Authors collection (boleh pakai slug atau name, asalkan nilainya aman di masing-masing file)
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
      # Hanya gunakan slug atau name jika sudah didefinisikan dan aman, lengkapi dengan /
      permalink: /authors/:name/

  # Posts collection: boleh pakai categories dan title
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:categories/:title/

  # Default layout untuk halaman lainnya
  - scope:
      path: ""
    values:
      layout: "default"


plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-paginate-multiple
  - jekyll-redirect-from
  - jekyll-include-cache
  - jekyll-minifier


paginate: 6
paginate_path: "/episodes/page:num/"


jekyll-minifier:
  preserve_php: true                # Default: false
  remove_spaces_inside_tags: true   # Default: true
  remove_multi_spaces: true         # Default: true
  remove_comments: true             # Default: true
  remove_intertag_spaces: true      # Default: false
  remove_quotes: false              # Default: false
  compress_css: true                # Default: true
  compress_javascript: true         # Default: true
  compress_json: true               # Default: true
  simple_doctype: false             # Default: false
  remove_script_attributes: false   # Default: false
  remove_style_attributes: false    # Default: false
  remove_link_attributes: false     # Default: false
  remove_form_attributes: false     # Default: false
  remove_input_attributes: false    # Default: false
  remove_javascript_protocol: false # Default: false
  remove_http_protocol: false       # Default: false
  remove_https_protocol: false      # Default: false
  preserve_line_breaks: false       # Default: false
  simple_boolean_attributes: false  # Default: false
  compress_js_templates: false      # Default: false
  preserve_patterns:                # Default: (empty)
  uglifier_args:                    # Default: (empty)
