name = "podcast-doctrineofdiscovery-v2"
compatibility_date = "2024-09-23"

[assets]
directory = "./_site"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
